services:
  gear-backend:
    container_name: gear-backends
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: production
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    ports:
      - 8000:8000